version: "3.8"
services:
  app-angular:
    container_name: "sbcontainer"
    build: .
    image: marcosep192000/front:ver1.0.0
    depends_on:
      - app
    ports:
      - "3000:3000"
    networks:
      - mired
  app:
    build: .
    image: marcosep192000/test:ver.1.1.2
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - JWT_SECRET=123456789654564564dsa65f4s56d4f65sdf56sd564f65sdf65sd6f54sd6f
    networks:
      - mired
  postgres_db:
    container_name: "postgres_db"
    image: "postgres:latest"
    ports:
      - "5432:5432"
    networks:
       - mired
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventario
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - mired
volumes:
  postgres-data:
networks:
  mired :
    driver: bridge