version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # ports:
    #   - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #   - "3001:8080"
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - DB_SSL=${DB_SSL}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    networks:
      - external_network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #     args:
  #       - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
  #       - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
  #       - NEXTAUTH_URL=${NEXTAUTH_URL}
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped
  # networks:
  #   - external_network
networks:
  external_network:
    external: true
